# -*- coding: utf-8 -*-
"""earring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14B6XZalYor-BUVKH3GKuaQ-NASQLIeTj
"""

!pip install opencv-python pillow numpy

!pip install mediapipe==0.10.13

import cv2
import numpy as np
import mediapipe as mp
from google.colab.patches import cv2_imshow
from PIL import Image
from google.colab import files

# Standard MediaPipe Setup
try:
    from mediapipe.solutions import face_mesh as mp_face_mesh
except:
    from mediapipe.python.solutions import face_mesh as mp_face_mesh

face_mesh = mp_face_mesh.FaceMesh(
    static_image_mode=True,
    max_num_faces=1,
    refine_landmarks=True
)
print("✅ Earring Engine Ready.")

uploaded = files.upload()

file_names = list(uploaded.keys())
# Detect earring (PNG) vs Face/Ear base (JPG)
earring_path = [f for f in file_names if f.lower().endswith('.png')][0]
base_path = [f for f in file_names if f != earring_path][0]

image = cv2.imread(base_path)
earring = cv2.imread(earring_path, cv2.IMREAD_UNCHANGED)

h, w, _ = image.shape
print(f"✅ Loaded Base: {base_path} | Loaded Earring: {earring_path}")

results = face_mesh.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

# List to store our earring positions
ear_positions = []

if not results.multi_face_landmarks:
    print("⚠️ No face detected. Defaulting to center.")
    ear_positions.append({'x': w // 2, 'y': h // 2, 'side': 'left'})
else:
    face_landmarks = results.multi_face_landmarks[0]

    # --- LEFT EAR (Camera Left) ---
    l_landmark = face_landmarks.landmark[137]
    lx = int(l_landmark.x * w)
    ly = int(l_landmark.y * h)
    # Push LEFT (subtract from x)
    lx = lx - int(w * 0.025)
    ear_positions.append({'x': lx, 'y': ly, 'side': 'left'})

    # --- RIGHT EAR (Camera Right) ---
    r_landmark = face_landmarks.landmark[366] # Equivalent edge for right side
    rx = int(r_landmark.x * w)
    ry = int(r_landmark.y * h)
    # Push RIGHT (add to x)
    rx = rx + int(w * 0.025)
    ear_positions.append({'x': rx, 'y': ry, 'side': 'right'})

# Visualize both points
temp = image.copy()
for pos in ear_positions:
    cv2.circle(temp, (pos['x'], pos['y']), 8, (0, 255, 0), -1)
print("📍 Dual Earring Anchors (Left & Right):")
cv2_imshow(temp)

# Scale based on image height for stability
# Adjust the 0.12 factor to make earrings larger/smaller
size_w = int(h * 0.12)
aspect = earring.shape[0] / earring.shape[1]
size_h = int(size_w * aspect)

# Enforce visibility for design details
if size_w < 45:
    size_w = 50
    size_h = int(size_w * aspect)

# For earrings, we usually keep them vertical (angle = 0)
# unless the head is tilted significantly.
angle = 0
if results.multi_face_landmarks:
    # Calculate head tilt
    l_eye = face_landmarks.landmark[33]
    r_eye = face_landmarks.landmark[263]
    angle = np.degrees(np.arctan2(r_eye.y - l_eye.y, r_eye.x - l_eye.x))

# Transform
(he, we) = earring.shape[:2]
M = cv2.getRotationMatrix2D((we//2, he//2), angle, 1.0)
ear_rotated = cv2.warpAffine(earring, M, (we, he), flags=cv2.INTER_LINEAR)
ear_resized = cv2.resize(ear_rotated, (size_w, size_h), interpolation=cv2.INTER_AREA)

print(f"📏 Earring size: {size_w}x{size_h}px")

def overlay_earring_dual(bg, overlay, x, y, side):
    oh, ow = overlay.shape[:2]

    # Flip the earring image for the right side so reflections look natural
    if side == 'right':
        overlay = cv2.flip(overlay, 1)

    x1 = x - ow // 2
    y1 = y - int(oh * 0.05)

    x2, y2 = x1 + ow, y1 + oh
    bg_h, bg_w = bg.shape[:2]
    tx1, ty1 = max(0, x1), max(0, y1)
    tx2, ty2 = min(bg_w, x2), min(bg_h, y2)

    if tx1 >= tx2 or ty1 >= ty2: return bg

    overlap_overlay = overlay[ty1-y1:ty2-y1, tx1-x1:tx2-x1]
    overlap_bg = bg[ty1:ty2, tx1:tx2]

    alpha = overlap_overlay[:, :, 3] / 255.0
    for c in range(3):
        bg[ty1:ty2, tx1:tx2, c] = (alpha * overlap_overlay[:, :, c] +
                                  (1 - alpha) * overlap_bg[:, :, c])
    return bg

# Apply to both sides
output = image.copy()
for pos in ear_positions:
    output = overlay_earring_dual(output, ear_resized, pos['x'], pos['y'], pos['side'])

print("✨ Final Dual Earring Result:")
cv2_imshow(output)
cv2.imwrite("dual_earring_output.png", output)