# -*- coding: utf-8 -*-
"""necklace.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZjwCGnhsvxxpPm5zNV57EvwaXNyE5KRq
"""

!pip install opencv-python numpy matplotlib

!pip install mediapipe==0.10.13

import cv2
import numpy as np
import mediapipe as mp
from google.colab.patches import cv2_imshow
from PIL import Image
from google.colab import files

# Standard MediaPipe Setup
try:
    from mediapipe.solutions import face_mesh as mp_face_mesh
except:
    from mediapipe.python.solutions import face_mesh as mp_face_mesh

face_mesh = mp_face_mesh.FaceMesh(
    static_image_mode=True,
    max_num_faces=1,
    refine_landmarks=True
)
print("✅ Necklace Engine Ready.")

uploaded = files.upload()

file_names = list(uploaded.keys())
necklace_path = [f for f in file_names if f.lower().endswith('.png') and "stock" not in f.lower()][0]
base_path = [f for f in file_names if f != necklace_path][0]

# Load base image
image_raw = cv2.imread(base_path, cv2.IMREAD_UNCHANGED)

# 🛠️ FIX: If the image has a transparent background, fill it with WHITE
if image_raw.shape[2] == 4:
    alpha_channel = image_raw[:, :, 3]
    rgb_channels = image_raw[:, :, :3]
    # Create white background
    white_bg = np.ones_like(rgb_channels, dtype=np.uint8) * 255
    # Blend
    alpha_factor = alpha_channel[:, :, np.newaxis] / 255.0
    image = (rgb_channels * alpha_factor + white_bg * (1 - alpha_factor)).astype(np.uint8)
else:
    image = image_raw

necklace = cv2.imread(necklace_path, cv2.IMREAD_UNCHANGED)

h, w, _ = image.shape
print(f"✅ Background processed. Ready for detection.")

# Convert to RGB for MediaPipe
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
results = face_mesh.process(image_rgb)

if not results.multi_face_landmarks:
    raise Exception("⚠️ No face detected. Ensure lighting is clear.")

face_landmarks = results.multi_face_landmarks[0]

# 📍 THE ANCHORS
chin = face_landmarks.landmark[152]
left_jaw = face_landmarks.landmark[234]
right_jaw = face_landmarks.landmark[454]

# Calculate pixel coordinates
cx, cy = int(chin.x * w), int(chin.y * h)

# 🛠️ THE FIX: Tighten the Y-offset
# We use a fraction of the distance between the nose and chin to keep it proportional
nose_tip = face_landmarks.landmark[4]
nose_to_chin_dist = abs(chin.y - nose_tip.y) * h

# Place necklace just 40% of that distance below the chin
neck_y = cy + int(nose_to_chin_dist * 0.20)
neck_x = cx
neck_x = neck_x + int(w * 0.01)

# Visualize
temp = image.copy()
cv2.circle(temp, (neck_x, neck_y), 10, (0, 255, 0), -1)
print("📍 Corrected Necklace Anchor (Center of Collarbone):")
cv2_imshow(temp)

# Scale based on Jaw Width (distance between 234 and 454)
jaw_width_px = np.linalg.norm(
    np.array([face_landmarks.landmark[234].x, face_landmarks.landmark[234].y]) -
    np.array([face_landmarks.landmark[454].x, face_landmarks.landmark[454].y])
) * w

# Adjust 1.5 to make it wider or narrower (1.3 to 1.6 is usually best)
size_w = int(jaw_width_px * 1.5)
aspect = necklace.shape[0] / necklace.shape[1]
size_h = int(size_w * aspect)

# Transformation
(hn, wn) = necklace.shape[:2]
# Match rotation to the tilt of the jaw
angle = np.degrees(np.arctan2(face_landmarks.landmark[454].y - face_landmarks.landmark[234].y,
                              face_landmarks.landmark[454].x - face_landmarks.landmark[234].x))

M = cv2.getRotationMatrix2D((wn//2, hn//2), angle, 1.0)
neck_rotated = cv2.warpAffine(necklace, M, (wn, hn), flags=cv2.INTER_LINEAR)
neck_resized = cv2.resize(neck_rotated, (size_w, size_h), interpolation=cv2.INTER_AREA)

print(f"📏 Necklace width scaled to jaw: {size_w}px")

def overlay_necklace_realistic(bg, overlay, x, y):
    oh, ow = overlay.shape[:2]

    # x is centered, y is the top of the necklace
    x1, y1 = x - ow // 2, y
    x2, y2 = x1 + ow, y1 + oh

    bg_h, bg_w = bg.shape[:2]
    tx1, ty1 = max(0, x1), max(0, y1)
    tx2, ty2 = min(bg_w, x2), min(bg_h, y2)

    if tx1 >= tx2 or ty1 >= ty2: return bg

    overlap_overlay = overlay[ty1-y1:ty2-y1, tx1-x1:tx2-x1]
    overlap_bg = bg[ty1:ty2, tx1:tx2]

    # Split channels
    overlay_bgr = overlap_overlay[:, :, :3]
    # 🛠️ THE FIX (Step 2 of 2): Inverse Alpha Multiplication
    # We use (Alpha * Overlay + (1-Alpha) * Background)
    # This creates a "tight" blend without the glowing halo effect
    overlay_alpha = overlap_overlay[:, :, 3] / 255.0
    overlay_alpha = np.expand_dims(overlay_alpha, axis=-1) # Add channel dim

    # Blend
    final_blend = (overlay_bgr * overlay_alpha) + (overlap_bg * (1 - overlay_alpha))

    # Paste back
    bg[ty1:ty2, tx1:tx2] = final_blend.astype(np.uint8)
    return bg

# Run the fixed overlay
output = image.copy()
output = overlay_necklace_realistic(output, neck_resized, neck_x, neck_y)

print("✨ Final Realism Fix Result:")
cv2_imshow(output)