# -*- coding: utf-8 -*-
"""nosering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTOh1uyfV0j4XZDIRAzRFPIYwtC_JrAh
"""

!pip install mediapipe==0.10.13

import cv2
import numpy as np
import mediapipe as mp
from google.colab.patches import cv2_imshow
from PIL import Image
from google.colab import files

# Robust MediaPipe Initialization
try:
    from mediapipe.solutions import face_mesh as mp_face_mesh
except ImportError:
    from mediapipe.python.solutions import face_mesh as mp_face_mesh

face_mesh = mp_face_mesh.FaceMesh(
    static_image_mode=True,
    max_num_faces=1,
    refine_landmarks=True
)
print("✅ Libraries and Face Mesh ready.")

from google.colab import files

uploaded = files.upload()

# Dynamically pick the filenames from the upload
# This prevents "File Not Found" errors if the name has (1) or (2) in it
file_names = list(uploaded.keys())
face_path = [f for f in file_names if "OIP" not in f][0] # Assumes face isn't named OIP
pin_path = [f for f in file_names if "OIP" in f][0]

image = cv2.imread(face_path)
pin = cv2.imread(pin_path, cv2.IMREAD_UNCHANGED)

if pin is None or pin.shape[2] != 4:
    print("❌ Warning: Pin image must be a PNG with a transparent background (Alpha channel)!")

h, w, _ = image.shape

results = face_mesh.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

if not results.multi_face_landmarks:
    raise Exception("No face detected! Try an image with a clearer view of the face.")

face_landmarks = results.multi_face_landmarks[0]

# 📍 LANDMARK SELECTION
# 242 sits on the fleshy part of the left nostril wing (matching your reference)
# 462 would be the equivalent for the right side
TARGET_LANDMARK = 134
landmark = face_landmarks.landmark[TARGET_LANDMARK]

x = int(landmark.x * w)
y = int(landmark.y * h)

# Visualize the placement point
temp = image.copy()
cv2.circle(temp, (x, y), 5, (0, 255, 0), -1)
print("📍 Anchor point moved to the upper nostril wing:")
cv2_imshow(temp)

# Scaling: Use the distance between eyes as a stable reference for pin size
eye_l = face_landmarks.landmark[133]
eye_r = face_landmarks.landmark[362]
face_scale = np.linalg.norm(np.array([eye_l.x, eye_l.y]) - np.array([eye_r.x, eye_r.y])) * w

# Adjust this factor (0.08) to make the pin bigger or smaller
size = int(face_scale * 0.25)
if size < 200: size = 110 # Minimum visibility threshold

# Rotation: Match the face tilt
dx = (face_landmarks.landmark[454].x - face_landmarks.landmark[234].x)
dy = (face_landmarks.landmark[454].y - face_landmarks.landmark[234].y)
angle = np.degrees(np.arctan2(dy, dx))

# Transform
(hp, wp) = pin.shape[:2]
center = (wp // 2, hp // 2)
M = cv2.getRotationMatrix2D(center, angle, 1.0)
pin_rotated = cv2.warpAffine(pin, M, (wp, hp), flags=cv2.INTER_LINEAR)
pin_resized = cv2.resize(pin_rotated, (size, size), interpolation=cv2.INTER_AREA)
print(f"📏 Pin resized to: {size}px")

def overlay_pin_perfect(bg, overlay, x, y):
    oh, ow = overlay.shape[:2]

    # For a pin, we center it EXACTLY on the landmark
    x1, y1 = x - ow // 2, y - oh // 2
    x2, y2 = x1 + ow, y1 + oh

    bg_h, bg_w = bg.shape[:2]
    tx1, ty1 = max(0, x1), max(0, y1)
    tx2, ty2 = min(bg_w, x2), min(bg_h, y2)

    if tx1 >= tx2 or ty1 >= ty2: return bg

    # Slice overlay and background
    overlap_overlay = overlay[ty1-y1:ty2-y1, tx1-x1:tx2-x1]
    overlap_bg = bg[ty1:ty2, tx1:tx2]

    # Optimized Alpha Blending
    alpha = overlap_overlay[:, :, 3] / 255.0
    for c in range(3):
        bg[ty1:ty2, tx1:tx2, c] = (alpha * overlap_overlay[:, :, c] +
                                  (1 - alpha) * overlap_bg[:, :, c])
    return bg

# Run and Show
output = image.copy()
output = overlay_pin_perfect(output, pin_resized, x, y)

print("✨ Final Nose Pin Result:")
cv2_imshow(output)
cv2.imwrite("nose_pin_output.png", output)